# Nome da aplicação
spring.application.name=digital-wallet-api

# Configurações do Banco de Dados PostgreSQL (Local)
spring.datasource.url=jdbc:postgresql://localhost:5432/wallet_db
spring.datasource.username=postgres
spring.datasource.password=123456
spring.datasource.driver-class-name=org.postgresql.Driver

# Configurações do Hibernate/JPA
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
# DESLIGAMOS a criação automática de tabelas pelo Hibernate (o Flyway vai cuidar disso)
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true

# Habilita o Flyway para gerenciar as Migrations
spring.flyway.enabled=true
